export type ColourType = {
  1: string,
  2?: string,
  3?: string,
  4?: string,
  5?: string,
  6?: string,
  7?: string,
  8?: string,
  9?: string,
  10?: string,
  11?: string,
};

export type ColoursType = {
  primary:ColourType,
  secondary:ColourType,
  neutral:ColourType,
  warning:ColourType,
  danger:ColourType,
  success:ColourType,
  info:ColourType,
  link: ColourType,
}

export type ThemeType = {
  maxColumns: number,
  body: string,
  danger: string,
  textDanger: string,
  alert: string,
  textAlert: string,
  neutral: string,
  textNeutral: string,
  neutralDark: string,
  textNeutralDark: string,
  success: string,
  textSuccess: string,
  primary: string,
  secondary: string,
  textPrimary: string,
  textSecondary: string,
  banner: string,
  subBanner: string,
  button: string,
  borderFaint: string,
  borderDark: string,
  alertMinHeight: string,
  sidebarWidth: string,
  buttonSubmitWidth: string,
  sidebarCollapsedWidth: string,
  sidebarHighlight: string,
  sidebarHighlightDark: string,
  sidebarItemHeight: string,
  sidebarActiveBorderWidth: string,
  headerHeight: string,
  collapseHeaderHeight: string,
  bodyPadding: string,
  tableRowHeight: string,
  containerWidth: string,
  signupContainerWidth: string,
  dropdownWidth: string,
  commisionInputWidth: string,
  colours: ColoursType,
  buttonHeight: string,
  smallButtonHeight: string,
  termsAndConditionsHeight: string,
  scrollWidth: string,
  toggleButtonSpacing: string,
  smModalWidth: string,
  loginFormWidth: string,
  loginFormArrow: string,
  addressSearchClose: string,
  boxShadow: {
    1: string,
    2: string,
  },
  borderWidth: {
    1: string,
    2: string,
    3: string,
  },
  borderRadius:{
    1: string,
    2: string,
  },
  padding: {
    1: string,
    2: string,
    3: string,
    4: string,
    5: string,
    6: string,
    7: string,
    8: string,
    9: string,
    10: string,
    11: string,
    12: string,
  },
  fontSize: {
    1: string,
    2: string,
    3: string,
    4: string,
    5: string,
    6: string,
    7: string,
    8: string,
    9: string,
    10: string,
  },
  fontWeight: {
    normal: string,
    bold: string,
    bolder: string,
  }
}
